ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

# Deploying your first Quarkus Panache application on OpenShift

## Develop your application:

Create your project:

[source,bash]
----
mvn io.quarkus:quarkus-maven-plugin:0.13.1:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=hibernate-panache \
    -DclassName="org.acme.rest.json.PersonResource" \
    -Dpath="/person" \
    -Dextensions="resteasy-jsonb,hibernate-orm-panache,jdbc-mariadb,smallrye-health"
----

And follow the instructions available on this guide: https://quarkus.io/guides/hibernate-orm-panache-guide

[NOTE]
====
Your database properties should look like these:

[source,properties]
----
quarkus.datasource.url=jdbc:mariadb://mariadb:3306/sparksjoy
quarkus.datasource.driver=org.mariadb.jdbc.Driver
quarkus.datasource.username=sparksjoy
quarkus.datasource.password=sparksjoy
quarkus.hibernate-orm.database.generation=update
----
====

## Build your application as a native image:

[source,bash]
----
./mvnw package -Pnative -Dnative-image.docker-build=true
----

## Deploy your application to OpenShift:

[source,bash]
----
oc new-build --binary --name=hibernate-panache
oc patch bc/hibernate-panache -p '{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"src/main/docker/Dockerfile.native"}}}}'
oc start-build hibernate-panache --from-dir=. --follow
oc new-app hibernate-panache
oc expose service hibernate-panache
----

WARNING: You only need to run the above steps once. Then your pipeline and application will already be setup.

## Redeploying your application to OpenShift:

TIP: You only need to start a new build to update your application.

Since your pipeline and application is already setup, you only need to start a new build: your application will be updated automatically.

Start a new build by running:

[source,bash]
----
oc start-build hibernate-panache --from-dir=. --follow
----

## Access your application running on OpenShift:

Get your application URL:

[source,bash]
----
oc get route hibernate-panache | awk '{print $2}'
----

TIP: Check your application on your OpenShift console.
