runtime:
  cache_dir: ./.cache/antora

site:
  title: Quarkus Tutorial
  url: https://redhat-developer-demos.github.io/quarkus-tutorial
  start_page: quarkus-tutorial::index.adoc

content:
  sources:
    - url: git@github.com:redhat-developer-demos/quarkus-tutorial.git
      tags: []
      branches: master
      start_path: documentation
asciidoc:
  attributes:
    tutorial-namespace: quarkustutorial
    quarkus-version: 1.2.0.Final
    minikube-version: 1.0.1+
    openshift-version: 3.11+
    minishift-version: 1.31+
    graalvm-version: 19.3.1
  extensions:
    - ./lib/copy-to-clipboard.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.0.4/ui-bundle.zip
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
