= Setup
include::_attributes.adoc[]

[[prerequisite]]
== Prerequisite Tools

=== IDE

You can use any Java IDE for this tutorial but if you didn't try it before, we recommend https://code.visualstudio.com/download[VS Code] with the https://code.visualstudio.com/docs/languages/java[Java Extension Pack].

[TIP]
====
If you are using vscode then install vscode https://aka.ms/vscode-remote/download/extension[Remote Development Extension pack],
which allows you to run this entire tutorial within a contianer that will have all tools configured.
====

=== CLI Tools

The following CLI tools are required for running the exercises in this tutorial.

ifndef::workshop[]
Kubernetes/OpenShift are required only in case you want to deploy the application into them.
endif::workshop[]

GraalVM is not mandatory if you have Docker installed.

[tabs]
====
Container Image::
+
--
If you have https://www.docker.com/products/docker-desktop[Docker for Mac or Windows or Linux]  then you can pull the linux container image 
https://quay.io/repository/rhdevelopers/tutorial-tools?tab=tags[tutorial tools] which has all the tools listed below installed and pre-configured.
[#docker-pull-tutorials-cli]
[source,bash]
-----
docker pull quay.io/rhdevelopers/tutorial-tools:0.0.3
mkdir quarkus-tutorial
cd quarkus-tutorial
mkdir work
docker run -ti -p 8080:8080 -v `pwd`/work:/work \
  -v `mvn help:evaluate -Dexpression=settings.localRepository | grep \
  -v '\[INFO\]'`:/opt/developer/.m2/repository 
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.3 bash

# -p will map Quarkus running in the container to your host port
# -v `pwd`... will map the host work subdirectory to the container /work directory, this is where you will create your application
# -v `mvn ...` will map your ~/.m2/repository of your host to the container repository to save downloading again between image runs
-----
copyToClipboard::docker-pull-tutorials-cli[]

Alternatively, you can chose to install things locally.
--
Locally::
+
--
Please have them installed and configured before you get started with any of the tutorial chapters.

[options="header"]
|===
|**Tool**|**macOS**|**Fedora**|**Windows**

ifndef::workshop[]
| **Kubernetes**
| `brew install kubernetes-cli`
| https://github.com/kubernetes/kubernetes/releases[Kubernetes Releases]
| https://github.com/kubernetes/kubernetes/releases[Kubernetes Releases]

|
| **(OR)**
|
|

| **OpenShift client(oc)**
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.8/openshift-client-mac-4.1.8.tar.gz[openshift-client-linux-4.x]
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.8/openshift-client-linux-4.1.8.tar.gz[openshift-client-linux-4.x]
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.8/openshift-client-windows-4.1.8.zip[openshift-client-linux-4.x]
endif::workshop[]

| **git**
| https://git-scm.com/download/mac
| `dnf install git`
| Make sure you have the https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux] installed

| **Docker**
| https://www.docker.com/products/docker-desktop[Docker Desktop for Mac]
| `dnf install docker`
| https://www.docker.com/products/docker-desktop[Docker Desktop for Windows]

| **Java 8**
| `brew tap AdoptOpenJDK/openjdk && brew cask install adoptopenjdk8`
| `dnf install java-1.8.0-openjdk.x86_64`
| https://adoptopenjdk.net[Windows] (Make sure you set the `JAVA_HOME` environment variable and add `%JAVA_HOME%\bin` to your `PATH`)

| **Apache Maven 3.6.0+**
| brew install maven
| dnf install maven
| https://maven.apache.org/download.cgi[Windows] (Make sure you set the `MAVEN_HOME` environment variable and add `%MAVEN_HOME%\bin` to your `PATH`)

| **Graal VM**
| https://github.com/oracle/graal/releases/download/vm-{graalvm-version}/graalvm-ce-darwin-amd64-{graalvm-version}.tar.gz[GraalVM Community Edition {graalvm-version}]
| https://github.com/oracle/graal/releases/download/vm-{graalvm-version}/graalvm-ce-linux-amd64-{graalvm-version}.tar.gz[GraalVM Community Edition {graalvm-version}]
| Not Supported

ifndef::workshop[]
| **stern**
| `brew install stern`
| https://github.com/wercker/stern/releases
| https://github.com/wercker/stern/releases
endif::workshop[]

|===
--
====

ifndef::workshop[]
[#remote-docker-repository]
== Remote Repository
For some parts of the tutorial, you will be pushing and pulling container images to and from a remote image repository. You will need an account with push rights. You can create a free account on https://quay.io[Red Hat Quay.io].
endif::workshop[]

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start setting up the environment, let's clone the tutorial sources and set the `TUTORIAL_HOME` environment variable to point to the root directory of the tutorial:

[#cloneRepo]
[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/quarkus-tutorial 
----
copyToClipboard::cloneRepo[]

The `work` folder in `$TUTORIAL_HOME` can be used to download the demo application resources and refer to them during the exercises. The `work` folder has a README with instructions on the source code repo and git commands to clone the sources.

NOTE: if you use `tutorial-tools`, this step is optional.

[IMPORTANT,subs="+macros,+attributes"]
====

This tutorial was developed and tested with:

- Quarkus `{quarkus-version}`
- Minikube `{minikube-version}`
- OpenShift `{openshift-version}`
- Minishift `{minishift-version}`
- Graal VM `{graalvm-version}`
====

ifndef::workshop[]
[#kubernetes-cluster]
== Kubernetes Cluster

[tabs]
====
Minikube::
+
--
[#quarkus-start-minikube]
[source,bash,subs="+macros,+attributes"]
----
minikube profile quarkus-tutorial && \
minikube -p quarkus-tutorial start --memory=8192 --cpus=4 --disk-size=50g && \
kubectl create namespace {tutorial-namespace}
kubectl config set-context --current --namespace={tutorial-namespace}
----
copyToClipboard::quarkus-start-minikube[]
--
Minishift::
+
--
[#quarkus-start-minishift]
[source,bash,subs="+macros,+attributes"]
----
minishift profile set quarkus-tutorial && \
minishift start --memory=8192 --cpus=4 --disk-size=50g && \
minishift addon enable admin-user && \
minishift addon enable anyuid && \
oc new-project {tutorial-namespace}
----
copyToClipboard::quarkus-start-minishift[]
--
====

[NOTE]
====
On macOS, you might need to install hyperkit and  pass it as the main engine adding `--vm-driver=hyperkit` after `--disk-size=50g`.
====

Prepare your shell environment

[#quarkus-tutorial-shell-env]
[source,bash,subs="+macros,+attributes"]
----
cd quarkus-tutorial
export TUTORIAL_HOME=pass:[`pwd`]
export GRAALVM_HOME='PUT THE LOCATION  WHERE YOU HAVE EXTRACTED GRAAL VM'
----
copyToClipboard::quarkus-tutorial-shell-env[]

Prepare your shell environment:

It is not necessary to install GraalVM as the native compilation can be done within a Docker container.
The only limitation, in this case, is to have Docker installed and the produced native executable will only be runnable inside a container.
GraalVM is already installed in `tutorial-tools`.

If you installed GraalVM, make sure to also install `native-image` 

[#quarkus-tutorial-graalvm-native]
[source,bash,subs="+macros,+attributes"]
----
gu install native-image
----
copyToClipboard::quarkus-tutorial-graalvm-native[]


[#quarkus-tutorial-shell-env]
[source,bash,subs="+macros,+attributes"]
----
cd quarkus-tutorial
export TUTORIAL_HOME=pass:[`pwd`]
export WORKSHOP_USER='PUT YOUR USERNAME HERE'
export GRAALVM_HOME='PUT THE LOCATION  WHERE YOU HAVE EXTRACTED GRAAL VM'
export WORKSHOP_OPENSHIFT_SERVER='PUT THE OPENSHIFT SEVER URL HERE'
----
copyToClipboard::quarkus-tutorial-shell-env[]

Login into OpenShift 
[#quarkus-tutorial-oc-login]
[source,bash,subs="+macros,+attributes"]
----
oc login --username pass:[$WORKSHOP_USER] --server pass:[$WORKSHOP_OPENSHIFT_SERVER] --insecure-skip-tls-verify=false
----
copyToClipboard::quarkus-tutorial-oc-login[]

ifdef::openshift-console-url[]
You can also access the Openshift Console via url {openshift-console-url}
endif::[]

IMPORTANT: If you are in `MAC OSX`, the variable should point to `Home` sub-directory: `export GRAALVM_HOME=$HOME/Development/graalvm/Contents/Home/`
endif::workshop[]

[#setup-work-folder]
== Work folder (Optional)

The work folder i.e `$TUTORIAL_HOME/work` can be used as a work directory during the build. 
