= Setup
include::_attributes.adoc[]

[[prerequisite]]
== Prerequisite Tools

=== IDE

You can use any Java IDE for this tutorial but if you didn't try it before, we recommend https://code.visualstudio.com/download[VS Code] with the https://code.visualstudio.com/docs/languages/java[Java Extension Pack].

=== CLI Tools

The following CLI tools are required for running the exercises in this tutorial. Please have them installed and configured before you get started with any of the tutorial chapters.

[cols="4*^,4*.",options="header"]
|===
|**Tool**|**macOS**|**Fedora**|**Windows**

| `Kubernetes`
| `brew install kubernetes-cli`
| https://github.com/kubernetes/kubernetes/releases[Kubernetes Releases]
| https://github.com/kubernetes/kubernetes/releases[Kubernetes Releases]

|
| **(OR)**
|
|

| `oc`
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-mac-4.1.8.tar.gz[openshift-client-linux-4.x]
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.1.8.tar.gz[openshift-client-linux-4.x]
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-windows-4.1.8.zip[openshift-client-linux-4.x]

| `git`
| https://git-scm.com/download/mac
| `dnf install git`
| Make sure you have the https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux] installed

| `Docker`
| https://www.docker.com/products/docker-desktop[Docker Desktop for Mac]
| `dnf install docker`
| https://www.docker.com/products/docker-desktop[Docker Desktop for Windows]

| Java 8
| `brew tap AdoptOpenJDK/openjdk && brew cask install adoptopenjdk8`
| `dnf install java-1.8.0-openjdk.x86_64`
| https://adoptopenjdk.net[Windows] (Make sure you set the `JAVA_HOME` environment variable and add `%JAVA_HOME%\bin` to your `PATH`)

| Apache Maven 3.6.0+
| brew install maven
| dnf install maven
| https://maven.apache.org/download.cgi[Windows] (Make sure you set the `MAVEN_HOME` environment variable and add `%MAVEN_HOME%\bin` to your `PATH`)

| Graal VM
| https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-darwin-amd64-19.1.1.tar.gz[graalvm-ce-19.1.1]
| https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-linux-amd64-19.1.1.tar.gz[graalvm-ce-19.1.1]
| https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-windows-amd64-19.1.1.zip[graalvm-ce-19.1.1]

| https://github.com/wercker/stern[stern]
| `brew install stern`
| `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`
| https://github.com/wercker/stern/releases

|===

[#remote-docker-repository]
== Remote Repository
For some parts of the tutorial, you will be pushing and pulling container images to and from a remote image repository. You will need an account with publish rights. As of this writing, knative works best with https://docker.io[Docker Hub].

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start setting up the environment, let's clone the tutorial sources and set the `TUTORIAL_HOME` environment variable to point to the root directory of the tutorial:

[#cloneRepo]
[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/quarkus-tutorial 
----
copyToClipboard::cloneRepo[]

The `work` folder in `$TUTORIAL_HOME` can be used to download the demo application resources and refer to them during the exercises. The `work` folder has a README with instructions on the source code repo and git commands to clone the sources.

[IMPORTANT,subs="+macros,+attributes"]
====

This tutorial was developed and tested with:

- Quarkus `{quarkus-version}`
- Minikube `{minikube-version}`
- OpenShift `{openshift-version}`
- Minishift `{minishift-version}`
- Graal VM `{graalvm-version}`
====

[#kubernetes-cluster]
== Kubernetes Cluster

ifndef::workshop[]

[tabs]
====
Minikube::
+
--
[#quarkus-start-minikube]
[source,bash,subs="+macros,+attributes"]
----
minikube profile quarkus-tutorial && \
minikube -p quarkus-tutorial start --memory=8192 --cpus=4 --disk-size=50g && \
kubectl create namespace {tutorial-namespace}
kubectl config set-context --current --namespace={tutorial-namespace}
----
copyToClipboard::quarkus-start-minikube[]
--
Minishift::
+
--
[#quarkus-start-minishift]
[source,bash,subs="+macros,+attributes"]
----
minishift profile set quarkus-tutorial && \
minishift start --memory=8192 --cpus=4 --disk-size=50g && \
minishift addon enable admin-user && \
minishift addon enable anyuid && \
oc new-project {tutorial-namespace}
----
copyToClipboard::quarkus-start-minishift[]
--
====
endif::[]

ifndef::workshop[]

Prepare your shell environment

[#quarkus-tutorial-shell-env]
[source,bash,subs="+macros,+attributes"]
----
cd quarkus-tutorial
export TUTORIAL_HOME=pass:[`pwd`]
export GRAALVM_HOME='PUT THE LOCATION  WHERE YOU HAVE EXTRACTED GRAAL VM'
----
copyToClipboard::quarkus-tutorial-shell-env[]
endif::[]

ifdef::workshop[]

Prepare your shell environment

[#quarkus-tutorial-shell-env]
[source,bash,subs="+macros,+attributes"]
----
cd quarkus-tutorial
export TUTORIAL_HOME=pass:[`pwd`]
export WORKSHOP_USER='PUT YOUR USERNAME HERE'
export GRAALVM_HOME='PUT THE LOCATION  WHERE YOU HAVE EXTRACTED GRAAL VM'
export WORKSHOP_OPENSHIFT_SERVER='PUT THE OPENSHIFT SEVER URL HERE'
----
copyToClipboard::quarkus-tutorial-shell-env[]

Login into OpenShift 
[#quarkus-tutorial-oc-login]
[source,bash,subs="+macros,+attributes"]
----
oc login --username pass:[$WORKSHOP_USER] --server pass:[$WORKSHOP_OPENSHIFT_SERVER] --insecure-skip-tls-verify=false
----
copyToClipboard::quarkus-tutorial-oc-login[]

ifdef::openshift-console-url[]
You can also access the Openshift Console via url {openshift-console-url}
endif::[]

endif::[]

[#setup-work-folder]
== Work folder (Optional)

The work folder i.e `$TUTORIAL_HOME/work` can be used as a work directory during the build. 
