= Basics and Fundamentals

include::_attributes.adoc[]

At the end of this chapter you will be able to :

* Create a Quarkus Java Application
* Build and run the Java application in JVM mode.
* Build and run the Java application in Native mode.
* Build and run the Java Application in Developer mode

[#basics-prerequisite]
== Prerequisite

include::partial$prereq-cli.adoc[]

[#basics-create-quarkus-app]
== Create Quarkus Application

Navigate to the tutorial's `work` folder:

[#basics-create-quarkus-project]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/work
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create
----
copyToClipboard::basics-create-quarkus-project[]

[#basics-ide-quarkus-app]
== Open the Project in IDE

Open or import the generated project into your IDE.

If you are using **vscode**, assuming your project name is `my-quarkus-project` then you can do like,

[#basics-ide-quarkus-project]
[source,bash,subs="+macros,+attributes"]
----
code my-quarkus-project
----
copyToClipboard::basics-ide-quarkus-project[]

NOTE: All further sections of this chapter assumes the application name to be `my-quarkus-project`.

[#basics-build-run-quarkus-app]
== Build and Run the Quarkus Application

include::ROOT:partial$compile-and-run.adoc[]

You can <<basics-call-svc>> to see a response like `hello`.

[#basics-run-quarkus-app-dev-mode]
== Run Quarkus Application in Development mode

Stop the Quarkus applicaiton that might be running in `jvm` or `native` mode. 

Run the following command to start Quarkus application in development mode:

[#basics-build-run-dev-mode]
[source,bash,subs="+macros,+attributes"]
----
./mvnw compile quarkus:dev 
----
copyToClipboard::basics-build-run-dev-mode[]

[#basics-update]
== Updating of code

NOTE: Only if running in Development mode

You can edit the Java source(s) in your IDE. When you save and hit refresh in your browser, you will notice browser showing the new changes.

[#basics-call-svc]
== Invoke Service
The simple `hello` REST URI can be called from the browser using http://localhost:8080 or using cli like: 

:doc-sec: basics
:k8s-cli: k8s
:path: hello
:k8s-env: minikube
:cli-tool: curl
:address: localhost
include::ROOT:partial$invoke-service.adoc[tag=call]
