=  Cloud Native Deployment

include::_attributes.adoc[]

At the end of this chapter you will be able to :

* Containerize the Quarkus Application
* Build and run the Quarkus Application in Kubernetes

[#conk8s-prerequisite]
== Prerequisite

include::partial$prereq-cli.adoc[]

[#conk8s-build-container-app]
== Containerize Quarkus Application

Navigate to the tutorial's `work` folder:

[#conk8s-nav-to-work-folder]
[source,bash,subs="+macros,+attributes"]
----
cd pass:[$TUTORIAL_HOME]/work
----
copyToClipboard::conk8s-nav-to-work-folder[]

NOTE: The instructions of this section assumes your project name to be `my-quarkus-project`

[tabs]
====
JVM mode::
+
--
[#conk8s-build-quarkus-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
cd my-quarkus-project && \
./mvnw clean package
----
copyToClipboard::conk8s-build-quarkus-jvm-app[]

After successful maven build, run the following command to build te container:

[#conk8s-build-quarkus-jvm-app-container]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.jvm -t example/my-quarkus-project-jvm .
----
copyToClipboard::conk8s-build-quarkus-jvm-app-container[]

Run the container to start the application in jvm mode

[#conk8s-build-run-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm -p 8080:8008 docker run example/my-quarkus-project-jvm
----
copyToClipboard::conk8s-build-run-jvm-app[]

--
Native mode::
+
--
[#conk8s-build-quarkus-native-app]
[source,bash,subs="+macros,+attributes"]
----
cd my-quarkus-project &&\
./mvnw clean package -Pnative -Dnative-image.docker-build=true <1>
----
copyToClipboard::conk8s-build-quarkus-native-app[]
<1> Using the `-Dnative-image.docker-build=true` is very important as need a linux native binary what will be containerized. 

NOTE: Native compilation will take few minutes to complete.

After successful maven build, run the following command to build te container:

[#conk8s-build-quarkus-native-app-container]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.native -t example/my-quarkus-project-native .
----
copyToClipboard::conk8s-build-quarkus-native-app-container[]

Run the container to start the application in native mode

[#conk8s-build-run-native-app]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm -p 8080:8008 docker run example/my-quarkus-project-native
----
copyToClipboard::conk8s-build-run-native-app[]


[WARNING]
=====
Tests will fail on Windows as there is no graalvm support for windows, you can workaround it using `-DskipTests` option.
=====
--
====

You can <<conk8s-call-svc>> to see a response like `hello`.
 
[#conk8s-call-svc]
== Invoke Service
The simple `hello` REST URI can be called via browser using http://localhost:8080 or using CLI like: 

:doc-sec: basics
:k8s-cli: k8s
:path: hello
:k8s-env: minikube
:cli-tool: curl
:address: localhost
include::ROOT:partial$invoke-service.adoc[tag=call]

[#conk8s-deploy-k8s-app]
== Deploy Quarkus Application in Kubernetes

Copy the pass:[$TUTORIAL_HOME]/templates/app.yaml to current Quarkus Application directory:

[#conk8s-copy-k8s-app-template]
[source,bash,subs="+macros,+attributes"]
----
cp pass:[$TUTORIAL_HOME]/templates/app.yaml .
----
copyToClipboard::conk8s-copy-k8s-app-template[]

Edit the app.yaml and replace the following variables:

[cols="3*^,3*.",options="header"]
|===
|**Variable**|**Description**|**Example**

| pass:[$APP_NAME]
| The Kubernetes application name
| my-quarkus-app

| pass:[$REGISTRY_USER_NAME]
| The container registry user name
| demo

| pass:[$APP_IMAGE]
| The Quarkus container image name 
| docker.io/demo/my-quarkus-project-native

|===

==== Deploy to Kubernetes

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#conk8s-run-deploy-k8s-app]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f pass:[$TUTORIAL_HOME]/work/my-quarkus-project/app.yaml
----
copyToClipboard::conk8s-run-deploy-k8s-app[]
--
oc::
+
--
endif::[]

[#conk8s-oc-run-deploy-k8s-app]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f pass:[$TUTORIAL_HOME]/work/my-quarkus-project/app.yaml
----
copyToClipboard::conk8s-oc-run-deploy-k8s-app[]
ifndef::workshop[]
--
====
endif::[]

==== Invoke Kubernetes Service
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#conk8s-run-deploy-oc-app]
[source,bash,subs="+macros,+attributes"]
----
kubectl get svc pass:[$APP_NAME]
----
copyToClipboard::conk8s-run-deploy-oc-app[]
--
oc::
+
--
endif::[]
With OpenShift we can create a route to make Quarkus application publicly accessible:

[#conk8s-oc-run-expose-svc]
[source,bash,subs="+macros,+attributes"]
----
oc expose service pass:[$APP_NAME]
----
copyToClipboard::conk8s-oc-run-expose-svc[]

Once the service is exposed we can use the following command to get the public url:

[#conk8s-oc-run-get-route]
[source,bash,subs="+macros,+attributes"]
----
oc get routes pass:[$APP_NAME]
----
copyToClipboard::conk8s-oc-run-get-route[]

Now you can use the URL to call the service from the browser or via cli.

ifndef::workshop[]
--
====
endif::[]