= Quarkus Extensions

include::_attributes.adoc[]
:quarkus-project-name: fruit-app
:svc-path: fruit
:experimental:

At the end of this chapter you will be able to :

* [x] What is Quarkus Extensions ?
* [x] How to add them to your Quarkus project?
* [x] How to make calls to other services with Rest Client
* [x] How to add fault tolerant behaviour in your service
* [x] How to add health checks

[#qext-intro]
== What are extensions ?
Extensions are set of dependencies that can added to the Quarkus project in need of a specific features e.g. health checks.  Extensions configure, boot and integrate a framework or technology into your Quarkus application. They also do all of the heavy lifting of providing the right information to GraalVM for your application to compile natively.

[#qext-list-extensions]
== Listing Extensions

The Quarkus maven plugin can list all available supported extensions. 

Navigate to the tutorial's `work` folder:

[#qext-nav-to-work-folder]
[source,bash,subs="+macros,+attributes"]
----
cd pass:[$TUTORIAL_HOME]/work
----
copyToClipboard::qext-nav-to-work-folder[]

NOTE: The instructions of this section assumes your project name to be `{quarkus-project-name}`

To list the available extensions, run the following command from your project directory.

[#qext-mvn-list-extensions]
[source,bash,subs="+macros,+attributes"]
----
cd my-quarkus-project && \
./mvnw quarkus:list-extensions
----
copyToClipboard::qext-mvn-list-extensions[]

[#qext-rest-client]
== Rest Client

In a microservices architecture, and generally speaking, any kind of application, might need to access other RESTful Web Services.
Quarkus provides a Rest client following the https://github.com/eclipse/microprofile-rest-client[MicroProfile Rest Client] spec.

Let's create a Rest client that access to http://www.fruityvice.com to get nutrition facts about fruits.
Two endpoints are the important ones for this workshop:

* `api/fruit/all` that returns all fruits.

[source, json]
----
[{
    "genus": "Malus",
    "name": "Apple",
    "id": 6,
    "family": "Rosaceae",
    "order": "Rosales",
    "nutritions": {
        "carbohydrates": 11.4,
        "protein": 0.3,
        "fat": 0.4,
        "calories": 52,
        "sugar": 10.3
    }
}, {...}
]
----

* `api/fruit/\{name\}` that returns specific info from given fruit name.

[source, json]
----
{
    "genus": "Musa",
    "name": "Banana",
    "id": 1,
    "family": "Musaceae",
    "order": "Zingiberales",
    "nutritions": {
        "carbohydrates": 22,
        "protein": 1,
        "fat": 0.2,
        "calories": 96,
        "sugar": 17.2
    }
}
----

[#qext-add-rest-client-extensions]
=== Adding Rest Client extension

:quarkus-rest-client-ext-name: quarkus-rest-client, quarkus-resteasy-jsonb

To add Rest Client and JSON-B extensions (`{quarkus-rest-client-ext-name}`) to the Quarkus application, run the following command from `{quarkus-project-name}` project directory:

[#qext-mvn-add-rest-client-extension]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -Dextension="{quarkus-rest-client-ext-name}"
----
copyToClipboard::qext-mvn-add-rest-client-extension[]

[#qext-create-fruity-vice-pojo]
=== Creating FruityVice POJO

We need to create a POJO object that is used to unmarshal JSON message from http://www.fruityvice.com to Java object.

Add new Java file in `$PROJECT_HOME/src/main/java/com/example` called `FruityVice` with the following contents:

[#quarkusrc-fruity-vice-pojo]
[source,java,subs="+macros,+attributes"]
----
package com.example;

public class FruityVice {

    public static FruityVice EMPTY_FRUIT = new FruityVice();

    private String name;
    private Nutritions nutritions;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Nutritions getNutritions() {
        return nutritions;
    }

    public void setNutritions(Nutritions nutritions) {
        this.nutritions = nutritions;
    }

    public static class Nutritions {
        private double fat;
        private int calories;

        public double getFat() {
            return fat;
        }

        public void setFat(double fat) {
            this.fat = fat;
        }

        public int getCalories() {
            return calories;
        }

        public void setCalories(int calories) {
            this.calories = calories;
        }

    }
}
----
copyToClipboard::quarkusrc-fruity-vice-pojo[]

[#qext-create-fruity-vice-service]
=== Creating FruityVice Service

The next thing is to create a Java interface that acts as a client between code and external service.

Add new Java file in `$PROJECT_HOME/src/main/java/com/example` called `FruityViceService` with the following contents:

[#quarkusrc-fruity-vice-service]
[source,java,subs="+macros"]
----
package com.example;

import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

@Path("/api")
@RegisterRestClient
public interface FruityViceService {

    @GET
    @Path("/fruit/all")
    @Produces(MediaType.APPLICATION_JSON)
    public List<FruityVice> getAllFruits();
    
    @GET
    @Path("/fruit/{name}")
    @Produces(MediaType.APPLICATION_JSON)
    public FruityVice getFruitByName(@PathParam("name") String name);

}
----
copyToClipboard::quarkusrc-fruity-vice-service[]

[#qext-create-fruity-vice-service-config]
=== Configuring FruityVice Service

Add the following properties to pass:[$PROJECT_HOME]/src/main/resources/application.properties:

[#quarkusrc-config-fruity-update-props]
[source,config,subs="+macros,+attributes"]
----
org.alexsotob.quickstart.FruityViceService/mp-rest/url=http://www.fruityvice.com
----
copyToClipboard::quarkusrc-config-fruity-update-props[]

[#qext-create-fruity-vice-service-resclient]
=== Using the RestClient

Open the following Java class pass:[$PROJECT_HOME]/src/main/java/com/example/FruitResource.java and copy the next content in its body:

[#quarkusrc-fruity-vice-service-inject]
[source,java,subs="+macros"]
----
@Inject
@RestClient
FruityViceService fruityViceService;

@GET
@Path("{name}")
@Produces(MediaType.APPLICATION_JSON)
public FruityVice getFruitInfoByName(@PathParam("name") String name) {
    return fruityViceService.getFruitByName(name);
}
----
copyToClipboard::quarkusrc-fruity-vice-service-inject[]

[#qext-rest-client-run-quarkus-app-dev-mode]
== Run Quarkus Application in Development mode

:section-build-run: rest-client

include::ROOT:partial$run-dev-mode.adoc[]

[#qext-call-fruity-rest-client]
=== Invoke Service
:doc-sec: rest-client
:k8s-cli: k8s
:path: fruit/banana
:k8s-env: minikube
:cli-tool: curl
:address: localhost

The simple `{path}` REST URI can be called via browser using http://localhost:8080/{path} or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[source,json]
----
{
    "name":"Banana",
    "nutritions":{
        "calories":96,
        "fat":0.2
    }
}
----

[#qext-fault-tolerance]
== Fault Tolerance

It is increasingly important to build fault tolerant micro services. Fault tolerance is about leveraging different strategies to guide the execution and result of some logic. Retry policies, bulkheads, and circuit breakers are popular concepts in this area. 
Quarkus integrates with https://github.com/eclipse/microprofile-fault-tolerance[MicroProfile Fault Tolerance] spec to provide resiliency capabilities.

[#qext-add-fault-tolerance-extensions]
=== Adding Fault Tolerance extension

:quarkus-fault-tolerance-ext-name: quarkus-smallrye-fault-tolerance

To add Fault Tolernace extension (`{quarkus-fault-tolerance-ext-name}`) to the Quarkus application, run the following command from `{quarkus-project-name}` project directory:

[#qext-mvn-add-fault-tolernace-extension]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -Dextension="{quarkus-fault-tolerance-ext-name}"
----
copyToClipboard::qext-mvn-add-fault-tolernace-extension[]

[#qext-retry-fruity-vice-service]
=== Add Retry to Fruity Vice Service

Let's add the retry policy in `FruityViceService`.

Add the following annotation to pass:[$PROJECT_HOME]/src/main/java/java/com/example/FruityViceService.java:

[#quarkusft-retry-fruit-vice-service]
[source,config,subs="+macros"]
----
@GET
@Path("/fruit/{name}")
@Produces(MediaType.APPLICATION_JSON)
@Retry(maxRetries = 3, delay = 2000)
public FruityVice getFruitByName(@PathParam("name") String name);
----
copyToClipboard::quarkusft-retry-fruit-vice-service[]

Now in case of any error, 3 retries are done automatically, waiting for 2 seconds between retries.

[#qext-fault-tolerance-run-quarkus-app-dev-mode]
=== Run Quarkus Application in Development mode

:section-build-run: fault-tolerance

include::ROOT:partial$run-dev-mode.adoc[]

[#qext-call-fruity-fault-tolerance-retry]
=== Invoke Service
:doc-sec: fault-tolerance-retry
:k8s-cli: cli
:path: fruit/banana
:k8s-env: minikube
:cli-tool: curl
:address: localhost

The simple `{path}` REST URI can be called via browser using http://localhost:8080/{path} or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[source,json]
----
{
    "name":"Banana",
    "nutritions":{
        "calories":96,
        "fat":0.2
    }
}
----

No change of previous calls done in <<Adding Rest Client extension>> section, but now switch off your network so you do not have access to http://www.fruityvice.com.
And make again a request to http://localhost:8080/{path}.

include::ROOT:partial$invoke-service.adoc[tag=call]

Now after waiting 6 seconds (3 retries x 2 seconds), the next exception is thrown `java.net.UnknownHostException: www.fruityvice.com`.

[#qext-fallback-fruity-vice-service]
=== Add Fallback to Fruity Vice Service

Let's add a fallback policy in case of an error in `FruityViceService`.

Add the following annotation to pass:[$PROJECT_HOME]/src/main/java/java/com/example/FruityViceService.java:

[#quarkusft-fallback-fruit-vice-service]
[source,config,subs="+macros"]
----
@GET
@Path("/fruit/{name}")
@Produces(MediaType.APPLICATION_JSON)
@Retry(maxRetries = 3, delay = 2000)
@Fallback(value = FruityViceRecovery.class)
public FruityVice getFruitByName(@PathParam("name") String name);

public static class FruityViceRecovery implements FallbackHandler<FruityVice> {

    @Override
    public FruityVice handle(ExecutionContext context) {
        return FruityVice.EMPTY_FRUIT;
	}

}
----
copyToClipboard::quarkusft-fallback-fruit-vice-service[]

Now in case of any error, 3 retries are done automatically, waiting for 2 seconds between retries. 
If the error persits, then the fallback method is executed.

[#qext-fault-tolerance-fallback-run-quarkus-app-dev-mode]
=== Run Quarkus Application in Development mode

:section-build-run: fault-tolerance-fallback

include::ROOT:partial$run-dev-mode.adoc[]

[#qext-call-fruity-fault-tolerance-fallback]
=== Invoke Service
:doc-sec: fault-tolerance-fallback
:k8s-cli: k8s
:path: fruit/banana
:k8s-env: minikube
:cli-tool: curl
:address: localhost

The simple `{path}` REST URI can be called via browser using http://localhost:8080/{path} or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

Now after waiting for 6 seconds (3 retries x 2 seconds), an empty object is sent instead of an exception.

[source,json]
----
{}
----

[#qext-circuit-breaker-fruity-vice-service]
=== Add Circuit Breaker to Fruity Vice Service

Let's add the circuit breaker policy in `FruityViceService`.

Remove previous annotations of fallback and retry policies and add the following annotation to pass:[$PROJECT_HOME]/src/main/java/java/com/example/FruityViceService.java:

[#quarkusft-circuit-breaker-fruit-vice-service]
[source,config,subs="+macros"]
----
@GET
@Path("/fruit/{name}")
@Produces(MediaType.APPLICATION_JSON)
@CircuitBreaker(requestVolumeThreshold = 4, failureRatio=0.75, delay = 5000)
public FruityVice getFruitByName(@PathParam("name") String name);

public static class FruityViceRecovery implements FallbackHandler<FruityVice> {

    @Override
    public FruityVice handle(ExecutionContext context) {
        return FruityVice.EMPTY_FRUIT;
	}

}
----
copyToClipboard::quarkusft-circuit-breaker-fruit-vice-service[]

Now, if 3 (4 x 0.75) failures occur among the rolling window of 4 consecutive invocations then the circuit is opened for 5000 ms and then be back to half open. 
If the invocation succeeds then the circuit is back to closed again.

[#qext-circuit-breaker-run-quarkus-app-dev-mode]
=== Run Quarkus Application in Development mode

:section-build-run: fault-tolerance-circuit-breaker

include::ROOT:partial$run-dev-mode.adoc[]

[#qext-call-fruity-fault-tolerance-circuit-breaker]
=== Invoke Service
:doc-sec: fault-tolerance-cb
:k8s-cli: k8s
:path: fruit/banana
:k8s-env: minikube
:cli-tool: curl
:address: localhost

Do 5 consecutive calls to the service, `{path}` REST URI can be called via browser using http://localhost:8080/{path} or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

The output changes form `java.net.UnknownHostException: www.fruityvice.com` in the first calls to `org.eclipse.microprofile.faulttolerance.exceptions.CircuitBreakerOpenException: getFruitByName` when circuit is opened.

The big difference between first exception and second one is that in first one, occurs because the circuit is closed and means that the system is trying to reach the host, in the second one, the circuit is closed and the exception is thrown automatically instead of trying to reach the host.

TIP: You can use `@Retry` and `@Fallback` annotations together with `@CircuitBreaker` annotation.

[#qext-turn-on-network]
=== Turn Network on

Turn network on again to continue with the workshop.

[#qext-health-checks]
== Health checks

If you had observed, the quarkus application deployed on Kubernetes does not have any health checks on it. As Kubernetes best practice its highly recommended that health checks be added to the all the deployments.

Health checks in Kubernetes can be added using https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[Liveness and Readiness] probes.

:quarkus-health-ext-name: quarkus-smallrye-health

[#qext-add-extensions]
=== Adding Health Check extension

We can add `{quarkus-health-ext-name}` extension to allow Quarkus application to be probed on the REST endpoint called `health` to know about its current health.

To add `{quarkus-health-ext-name}` to the Quarkus application, run the following command from `{quarkus-project-name}` project directory:

[#qext-mvn-add-extension]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -Dextension="{quarkus-health-ext-name}"
----
copyToClipboard::qext-mvn-add-extension[]

After successful execution of the above command, you will have the following dependency added to the `{quarkus-project-name}` project's pom.xml:

.pom.xml 
[source,xml]
----
...
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
...
----

[#qext-rebuild-container-images]
=== Rebuild container images

Let us rebuild the application after adding the health check extensions

:section-k8s: health-check
include::ROOT:partial$build-containers.adoc[tag=build]

[#qext-check-health-endpoint]
=== Checking health check endpoint

Lets start the newly built container:

include::ROOT:partial$build-containers.adoc[tag=run]

After adding `smallrye-health` extension we should have REST endpoint called `/health` available. Lets invoke the `/health` endpoint to check the health of the Quarkus application.

[#qext-call-health-ep]
=== Invoke Service
:doc-sec: basics-health-check
:k8s-cli: k8s
:path: health
:k8s-env: minikube
:cli-tool: curl
:address: $(minikube ip)

The simple `{path}` REST URI can be called via browser using `http://$(minikube ip):8080/{path}` or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[source,json]
----
{
    "checks": [],
    "outcome": "UP"
}
----

Then you can stop the container by typing kbd:[Ctrl+C].

[#qext-add-probes-to-k8s]
=== Add probes to Kubernetes Quarkus Application

We need to push the rebuilt containers to the container registry.

include::ROOT:partial$build-containers.adoc[tag=tag-push]

[#qext-health-check-k8s-delete-resources]
=== Delete Kubernetes Resources

:section-k8s: probes
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-delete]

[#qext-health-check-k8s-apply-resources]
=== Apply Kubernetes Resources

Since we are using Kubernetes extension, configured at xref:03-containers-kubernetes.adoc[Cloud Native Deployment] section, the kubernetes resource has been updated with both probes.

[#quarkusk8s-generated-kubernetes-resource-health-check]
[source,bash,subs="+macros,+attributes"]
----
cat pass:[$TUTORIAL_HOME]/target/wiring-classes/META-INF/kubernetes/kubernetes.json
----
copyToClipboard::quarkusk8s-generated-kubernetes-resource-health-check[]

include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-deploy]

[#qext-health-check-invoke-k8s-svc]
=== Invoke Kubernetes Service

include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-invoke-svc]


[#qext-custom-health-check]
=== Customizing Health Checks

So far, you've seen that some a default health check is provided but in most cases, you'd like to customize this logic providing custom logic.
Moreover, Kubernetes provides the concept of liveness and readiness probe to regularly check the health of the application.

liveness:: Checks if the application is up and running.
readiness:: Checks if the application can receive public requests.

Let's create a custom check for both liveness and readiness checks.
Add new Java file in `$PROJECT_HOME/src/main/java/com/example` called `FruitHealthCheck` with the following contents:

[#quarkusp-fruit-checks]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;

import org.eclipse.microprofile.health.HealthCheck;
import org.eclipse.microprofile.health.Liveness;
import org.eclipse.microprofile.health.Readiness;

import io.smallrye.health.HealthStatus;

@ApplicationScoped
public class FruitHealthCheck {

    @Produces
    @ApplicationScoped
    @Liveness
    HealthCheck liveCheck() {
      return HealthStatus.up("successful-live");
    }

    @Produces
    @ApplicationScoped
    @Readiness
    HealthCheck readyCheck() {
      return HealthStatus.state("successful-read", this::isReady)
    }

    private boolean isReady() {
        return true;
    }
}
----
copyToClipboard::quarkusp-fruit-checks[]

[#qext-rebuild-container-images-custom-check]
=== Rebuild container images

Let us rebuild the application after adding the health check extensions

:section-k8s: custom-check
include::ROOT:partial$build-containers.adoc[tag=build]

[#qext-check-custom-health-endpoint]
=== Checking health check endpoint

Lets start the newly built container:

include::ROOT:partial$build-containers.adoc[tag=run]

After adding `smallrye-health` extension we should have REST endpoint called `/health` available. Lets invoke the `/health` endpoint to check the health of the Quarkus application and you'll see both health checks.

[#qext-call-health-custom]
=== Invoke Service
:doc-sec: custom-health
:k8s-cli: k8s
:path: health
:k8s-env: minikube
:cli-tool: curl
:address: $(minikube ip)

The simple `{path}` REST URI can be called via browser using `http://$(minikube ip)/{path}` or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[source,json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "successful-live",
            "status": "UP"
        },
        {
            "name": "successful-read",
            "status": "UP"
        }
    ]
}
----

But also you can invoke them individually by calling `/health/live` and `/health/ready`.

:doc-sec: custom-health-live
:path: health/live
include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[source, json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "successful-live",
            "status": "UP"
        }
    ]
}
----

:doc-sec: custom-health-ready
:path: health/ready
include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[source, json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "successful-read",
            "status": "UP"
        }
    ]
}
----

Then you can stop the container by typing kbd:[Ctrl+C].

[#qext-add-custom-probes-to-k8s]
=== Add probes to Kubernetes Quarkus Application

We need to push the rebuilt containers to the container registry.

include::ROOT:partial$build-containers.adoc[tag=tag-push]

[#qext-custom-health-check-k8s-delete-resources]
=== Delete Kubernetes Resources

:section-k8s: custom-probes
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-delete]

[#qext-custom-health-check-k8s-apply-resources]
=== Apply Kubernetes Resources

Since we are using Kubernetes extension, configured at xref:03-containers-kubernetes.adoc[Cloud Native Deployment] section, the kubernetes resource has been updated with both probes.

[#quarkusk8s-generated-kubernetes-resource-custom-health-check]
[source,bash,subs="+macros,+attributes"]
----
cat pass:[$TUTORIAL_HOME]/target/wiring-classes/META-INF/kubernetes/kubernetes.json
----
copyToClipboard::quarkusk8s-generated-kubernetes-resource-custom-health-check[]

include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-deploy]

[#qext-custom-health-check-invoke-k8s-svc]
=== Invoke Kubernetes Service

include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-invoke-svc]

[#qext-custom-health-check-end-k8s-delete-resources]
=== Delete Kubernetes Resources

:section-k8s: health-check
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-delete]