= Build Database Interactive Applications

include::_attributes.adoc[]
:quarkus-project-name: fruits-app
:svc-path: fruit

At the end of this chapter you will be able to :

* [x] What is Panache ?
* [x] How to build a Hibernate application using Panache?

[#quarkusp-demo-overview]
== Demo Overview 

You'll learn how easy and productive is Quarkus with Hibernate with Panache. For this, we'll developer an application called "Fruits". It's a simple CRUD REST API that handles information about fruits.

We'll use http://www.h2database.com[H2] as our backing database, but it's very easy to use other database engines with Quarkus. As an exercise for later, we suggest you to try your favorite database engine with the documentation found https://quarkus.io/guides/datasource[here].

=== Build Fruit Resource

The skeleton project to get started is the same you created at xref:02-basics-fundas.adoc[Basics and Fundamentals].

NOTE: For the easier reference, we shall call the `fruits-app` project folder as pass:[$PROJECT_HOME]

[#quarkusp-add-persistence-extensions]
==== Add Extensions

[#qext-mvn-add-persistence-extensions]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -Dextension="quarkus-resteasy-jsonb, quarkus-jdbc-h2, quarkus-hibernate-orm-panache, quarkus-smallrye-openapi"
----

[#quarkusp-configure-props]
==== Edit the application.properties

Add the following properties to `pass:[$PROJECT_HOME]/src/main/resources/application.properties`:

[#quarkuspdb-update-props]
[.console-input]
[source,config,subs="+macros,+attributes"]
----
quarkus.datasource.url=jdbc:h2:mem:default
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=username-default
quarkus.datasource.min-size=3
quarkus.datasource.max-size=13
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
----

==== Test Database connection

Let's start Quarkus in `development` mode to verify the database connection works:

[#quarkuspdb-test-dbconn]
[.console-input]
[source,config,subs="+macros,+attributes"]
----
./mvnw compile quarkus:dev
----

If all went well then you should be seeing something like the following in the log:

[.console-output]
[source,bash]
----
Listening for transport dt_socket at address: 5005
2020-02-18 09:57:23,827 WARN  [io.qua.agr.dep.AgroalProcessor] (build-23) Agroal dependency is present but no driver has been defined for the default datasource
2020-02-18 09:57:25,322 INFO  [io.quarkus] (main) devnexus 1.0-SNAPSHOT (running on Quarkus 1.2.0.Final) started in 2.287s. Listening on: http://0.0.0.0:8080
2020-02-18 09:57:25,324 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-02-18 09:57:25,324 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, narayana-jta, resteasy, resteasy-jsonb, smallrye-openapi, swagger-ui]
----

As you would have noticed there is no database logs. That's because we dont have any database related code yet:

[#quarkusp-create-fruit-entity]
==== Create Fruit Entity

Add new Java file in `$PROJECT_HOME/src/main/java/com/example` called `Fruit` with the following contents:

[#quarkusp-fruit-entity]
[.console-input]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import javax.persistence.Entity;

@Entity
public class Fruit {

    public String name;

    public String season;

}
----

[#quarkusp-edit-fruit-resource]
==== Update Fruit Resource

Edit the Java file `$PROJECT_HOME/src/main/java/com/example/FruitResource.java`, remove `hello()` method and add a new REST method to get all the available fruits:

[#quarkusp-fruit-entity1]
[.console-input]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/fruit")
public class FruitResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<Fruit> fruits() {
        return Fruit.listAll(); <1>
    }

}
----

<1> Your IDE will show an errors in `FruitResource.java` as it does not have a method `listAll()` in `Fruit` entity class.

Do I need to add it ? The simple answer is **NO**.

[#quarkusp-what-is-panache]
==== Make Fruit Entity a Panache Entity 

****

**What is Panache ?**

Hibernate ORM is the de facto JPA implementation and offers you the full breadth of an Object Relational Mapper. It makes complex mappings possible, but it does not make simple and common mappings trivial. Hibernate ORM with Panache focuses on making your entities trivial and fun to write in Quarkus.

More info https://quarkus.io/guides/hibernate-orm-panache-guide[Panache Guide]

****

[#quarkusp-fruit-entity2]
[.console-input]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import javax.persistence.Entity;
import io.quarkus.hibernate.orm.panache.PanacheEntity;

@Entity
public class Fruit extends PanacheEntity {

    public String name;

    public String season;

}
----

Making the `Fruit` entity as a `Panache Entity` will make it both Entity and DAO and ofcourse the error in the `FruitResource.java` disappears.

Let's now access the Fruits API http://localhost:8080/fruit. If all goes well you will see some Hibernate SQL statements in the log that will create the new table `Fruit` with columns from `Fruit.java` entity class.

Since we don't have any fruits in the DB you would have got an empty response back. 

Let's add a REST method to the `FruitResource.java` to save a 'Fruit':

[#quarkusp-fruit-add-persist]
[.console-input]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import java.util.List;

import javax.transaction.Transactional;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

@Path("/fruit")
public class FruitResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<Fruit> fruits() {
        return Fruit.listAll();
    }

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Transactional
    public Response newFruit(Fruit fruit) {
        fruit.id = null;
        fruit.persist();
        return Response.status(Status.CREATED).entity(fruit).build();
    }

}
----

You can insert a new fruit by using the next `curl` command: `curl -vvv -d '{"name": "Banana", "season": "Summer"}' -H "Content-Type: application/json" POST http://localhost:8080/fruit`

Or use the Swagger UI at http://localhost:8080/swagger-ui to try your REST endpoints. 

Try adding a fruit via the Swagger UI Post and try listing the available fruits. You will see a JSON response like this one:

[.console-output]
[source,json]
----
{
    "name": "Banana",
    "season": "Summer"
}
----

NOTE: The response may vary based on which fruits you added.

[#quarkusp-fruits-finder]
==== Finders 
Cool! So far we did with some primitive methods lets explore some cool things that Panache offers. 

Let's try to find all fruits by a season. To make the query return some data let us add some fruits to the DB.

Create the following `import.sql` file in `$PROJECT_HOME/src/main/resources`:

[#quarkusp-add-fruits]
[.console-input]
[source,sql,subs="+macros,+attributes"]
----
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Mango','Spring');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Strawberry','Spring');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Orange','Winter');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'GrapeFruit','Winter');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Blueberry','Summer');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Banana','Summer');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Plum','Summer');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Apple','Fall');
INSERT INTO Fruit(id,name,season) VALUES (nextval('hibernate_sequence'),'Grapes','Fall');
----

Update `Fruit` entity to add a finder method like: 

[#quarkusp-find-fruits]
[.console-input]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import java.util.List;
import javax.persistence.Entity;
import io.quarkus.hibernate.orm.panache.PanacheEntity;

@Entity
public class Fruit extends PanacheEntity {

    public String name;

    public String season;

    public static List<Fruit> getAllFruitsForSeason(String season) {
        return find("season", season).list();
    }

}
----


Update `FruitResource` by adding a REST endpoint to get fruits by season: 

[#quarkusp-get-find-fruits]
[.console-input]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import java.util.List;

import javax.transaction.Transactional;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

@Path("/fruit")
public class FruitResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<Fruit> fruits() {
        return Fruit.listAll();
    }

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/{season}")
    public List<Fruit> fruitsBySeason(@PathParam("season") String season) {
        return Fruit.getAllFruitsForSeason(season);
    }

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Transactional
    public Response newFruit(Fruit fruit) {
        fruit.id = null;
        fruit.persist();
        return Response.status(Status.CREATED).entity(fruit).build();
    }

}
----

To test finder use the Swagger UI http://localhost:8080/swagger-ui. 

A finder for fruits for the __Summer__ season should return a response like :

[.console-output]
[source,json]
----
[
  {
    "id": 5,
    "name": "Blueberry",
    "season": "Summer"
  },
  {
    "id": 6,
    "name": "Banana",
    "season": "Summer"
  },
  {
    "id": 7,
    "name": "Plum",
    "season": "Summer"
  }
]
----

[#quarkusp-testing]
=== Testing Fruit Resource

Let's write a test to validate that inserting and finding methods works as expected.

[#quarkusp-testing-dep]
==== Adding AssertJ Dependency

To validate simple output messages RestAssured assertions mechanism is enough but in our experience, when start dealing with more complex assertions then things might become a bit more complex. 
For this reason, we encourage you to start using https://assertj.github.io/doc/[AssertJ].

Open `$PROJECT_HOME/pom.xml` and add the following dependencies in the `dependencies` section:

[#quarkusp-register-assertj]
[.console-input]
[source,xml,subs="+macros,+attributes"]
----
<dependency>
    <groupId>org.assertj</groupId>
    <artifactId>assertj-core</artifactId>
    <version>3.13.2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-test-h2</artifactId>
    <version>1.2.0.Final</version>
    <scope>test</scope>
</dependency>
----

[#quarkusp-write-persistence-test]
==== Write Persistence Test 

Open the next class `$PROJECT_HOME/src/test/java/com/example/FruitResourceTest.java` and copy the next content:

[#quarkusp-test-class]
[.console-input]
[source,java,subs="+macros"]
----
package com.example;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.h2.H2DatabaseTestResource;
import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
@TestMethodOrder(OrderAnnotation.class)
@QuarkusTestResource(H2DatabaseTestResource.class)
public class FruitResourceTest {

    @Test
    @Order(1)
    public void testInsertFruit() {
        Fruit fruit = new Fruit();
        fruit.name = "Watermelon";
        fruit.season = "Summer";

        given()
          .contentType("application/json")
          .body(fruit)
          .when()
          .post("/fruit")
          .then()
          .assertThat()
          .statusCode(201);
    }

    @Test
    @Order(2)
    public void testFindFruitsBySeason() {
        final List<Fruit> fruits = given()
          .when()
          .get("/fruit/{season}", "Summer")
          .then()
          .assertThat()
          .statusCode(200)
          .extract()
          .body()
          .jsonPath()
          .getList(".", Fruit.class);

        assertThat(fruits)
            .extracting("name")
            .containsExactlyInAnyOrder("Banana", "Watermelon", "Plum", "Blueberry");
    }

}
----

include::ROOT:partial$invoke-service.adoc[tag=test]

ifndef::workshop[]

////
[#quarkusp-cloud-dev]
=== Deploy on Kubernetes

If you are using Kubernetes/OpenShift instead of Docker you can deploy the application to Kubernetes/OpenShift following the next steps:

We need to build the `{quarkus-project-name}` application and container before deploying them on kubernetes.

NOTE: You can stop the `port-forward` and Quarkus application running in development mode 

[#quarkusp-cloud-dev-build-container]
==== Build the application container

:quarkus-project-name: fruit-app
:section-k8s: persistence
include::ROOT:partial$build-containers.adoc[tag=build]

[#quarkusp-cloud-dev-prepare-app]
==== Prepare the Kubernetes Deployment

include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-prep]

==== Tag and Push the application container

As we have already built the container images, we might need to build and push it to remote container registry. The remote images from the container registry will be used in kubernetes deployments:

With example variable settings as above, run the following commands to tag the images:

:doc-sec: tag-push-panache
include::ROOT:partial$build-containers.adoc[tag=tag-push]

[#quarkusp-cloud-dev-apply-resources]
==== Apply Resources

Once the images has been pushed to container registry, run the following command to deploy the application to kubernetes:

:doc-sec: k8s-deploy-panache
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-deploy]

[#quarkusp-invoke-k8s-svc]
==== Invoke Kubernetes Service

:doc-sec: k8s-invoke-panache
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-invoke-svc]

NOTE: `swagger-ui` is available only for `dev` and `test`, you can use REST API tools to access API.

[#quarkusp-persistence-k8s-delete-resources]
=== Delete Kubernetes Resources

:section-k8s: persistence
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-delete]

endif::workshop[]
////
