= REST Client

A typical scenario in a Microservices architecture is the remote invocation of remote REST HTTP endpoints. Quarkus provides a typed REST client that follows the  https://github.com/eclipse/microprofile-rest-client[MicroProfile REST Client, window=_blank] specification.

Let's create a REST client that accesses https://swapi.dev[window=_blank] to get additional information about Movies. The endpoint we're interested in is this one:

* `api/films/?search=\{title\}`, which returns specific info about the given movie.

[.console-output]
[source, json]
----
{
    "count": 1, 
    "next": null, 
    "previous": null, 
    "results": [
        {
            "title": "The Empire Strikes Back", 
            "episode_id": 5, 
            "opening_crawl": "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space....", 
            "director": "Irvin Kershner", 
            "producer": "Gary Kurtz, Rick McCallum", 
            "release_date": "1980-05-17",            
            "created": "2014-12-12T11:26:24.656000Z", 
            "edited": "2014-12-15T13:07:53.386000Z", 
            "url": "https://swapi.dev/api/films/2/"
        }
    ]
}
----

== Add the REST Client extension

Open a new terminal window, and make sure you’re at the root of your `{project-name}` project, then run:

[tabs]
====
Maven::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -D"extensions=rest-client, rest-client-jackson"
----

--
Quarkus CLI::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
quarkus extension add rest-client rest-client-jackson
----
--
====


[.console-output]
[source,text]
----
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< com.redhat.developers:tutorial-app >-----------------
[INFO] Building tutorial-app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:3.10.2:add-extension (default-cli) @ tutorial-app ---
✅ Adding extension io.quarkus:quarkus-rest-client-jackson
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.773 s
[INFO] Finished at: 2024-05-23T21:43:38-04:00
[INFO] ------------------------------------------------------------------------
----

Notice in the logs how Quarkus is reloading and the `rest-client-jackson` extension is now part of the `Installed features`.

== Create FruityVice POJO

We need to create a POJO object that is used to unmarshal a JSON message from http://swapi.dev[window=_blank].

Create a new `Swapi` Java class in `src/main/java` in the `com.redhat.developers` package with the following contents:

[.console-input]
[source,java]
----
package com.redhat.developers;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Swapi {
        
    private List<Results> results;

    public Swapi(@JsonProperty("results") List<Results> results) {
        this.results = results;
    }

    public List<Results> getResults() {
        return results;
    }
    
    public static class Results {
        private int episodeId;
        private String producer;
        private String director;
        private String opening_crawl;

        public Results(int episodeId, String producer, String director, String opening_crawl) {
            this.episodeId = episodeId;
            this.producer = producer;
            this.director = director;
            this.opening_crawl = opening_crawl;
        }

        public int getEpisodeId() {
            return episodeId;
        }

        public String getProducer() {
            return producer;
        }

        public String getDirector() {
            return director;
        }

        public String getOpening_crawl() {
            return opening_crawl;
        }       
    }
}
----

=== Create SwapiService

Now we're going to implement a Java interface that mimics the remote REST endpoint.

Create a new `SwapiService` Java interface in `src/main/java` in the `com.redhat.developers` package with the following contents:

[.console-input]
[source,java]
----
package com.redhat.developers;

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.MediaType;

import com.redhat.developers.Swapi.Results;

@Path("/api")
@RegisterRestClient
public interface SwapiService {
    @GET
    @Path("/films")
    @Produces(MediaType.APPLICATION_JSON)
    Swapi getMovieByTitle(@QueryParam("search") String title);

}
----

== Configure REST Client properties

Add the following properties to your `application.properties` in `src/main/resources`:

[.console-input]
[source,properties]
----
quarkus.rest-client."com.redhat.developers.SwapiService".url=https://swapi.dev
----

== Create MovieDTO

We're going to enhance our `MovieResource` endpoint by creating a new `MovieDTO` POJO and add the additional information provided by the `SwapiService`.

Create a new `MovieDTO` Java class in `src/main/java` in the `com.redhat.developers` package with the following contents:

[.console-input]
[source,java]
----
package com.redhat.developers;

import java.sql.Date;
import java.util.List;

import com.redhat.developers.Swapi.Results;

public class MovieDTO {
    private String title;
    private Date releaseDate;
    private int episodeId;
    private String producer;
    private String director;
    private String opening_crawl;

    private MovieDTO(String title, Date releaseDate, int episodeId, String producer, String director, String opening_crawl) {
        this.title = title;
        this.releaseDate = releaseDate;
        this.episodeId = episodeId;
        this.producer = producer;
        this.director = director;
        this.opening_crawl = opening_crawl;
    }

    public static MovieDTO of(Movie movie, Swapi swapi){
        List<Results> results = swapi.getResults();
        Results result = results.get(0);
        
        return new MovieDTO(
            movie.title,
            movie.releaseDate,
            result.getEpisodeId(),
            result.getProducer(),
            result.getDirector(),
            result.getOpening_crawl()
        );
    }

    public String getTitle() {
        return title;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }

    public int getEpisodeId() {
        return episodeId;
    }

    public String getProducer() {
        return producer;
    }

    public String getDirector() {
        return director;
    }

    public String getOpening_crawl() {
        return opening_crawl;
    }
}
----

== Change MovieResource to use SwapiService

Now that we have all the required classes, we can change `MovieResource` to get movies by title and use our `SwapiService` REST client via the `@RestClient` annotation.

Change the `MovieResource` Java class in `src/main/java` in the `com.redhat.developers` package with the following contents:

[.console-input]
[source,java]
----
package com.redhat.developers;

import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.microprofile.rest.client.inject.RestClient;

import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.Status;

@Path("/movie")
public class MovieResource {

    @RestClient
    @Inject
    SwapiService swapiService;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<MovieDTO> movies(@QueryParam("year") String year) {
        if (year != null) {
            return Movie.findByYear(Integer.parseInt(year)).stream()
            .map(movie -> MovieDTO.of(movie, swapiService.getMovieByTitle(movie.title)))
            .collect(Collectors.toList());
        }
        return Movie.<Movie>listAll().stream()
            .map(movie -> MovieDTO.of(movie, swapiService.getMovieByTitle(movie.title)))
            .collect(Collectors.toList());
    }

    @Transactional
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response newMovie(Movie movie) {
        movie.id = null;
        movie.persist();
        return Response.status(Status.CREATED).entity(movie).build();
    }
}
----

== Invoke the endpoint

You can check your new implementation using a REST client by pointing your browser to http://localhost:8080/movie?year=1980[window=_blank]

You can also run the following command:

[.console-input]
[source,bash]
----
curl -w '\n' localhost:8080/movie?year=1980
----

[.console-output]
[source,json]
----
[
  {
    "title": "The Empire Strikes Back",
    "releaseDate": "1980-05-17",
    "episodeId": 0,
    "producer": "Gary Kurtz, Rick McCallum",
    "director": "Irvin Kershner",
    "opening_crawl": "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space...."
  }
]
----
