= Configuration

:project-name: fruits-app

Hardcoded values in your code is a no go, so let's see how to add configuration to your application. 
Quarkus relies on the MicroProfile Config specification and the main configuration file is  `application.properties`.

== Using a config property in your code

Let's change our `GreetingResource` class to use a configuration property. Change its content to:

[.console-input]
[source,java]
----
package com.redhat.developers;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/hello")
public class GreetingResource {

    @ConfigProperty(name = "greeting")
    String greeting;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return greeting;
    }
}
----

If you refresh your browser pointing to http://localhost:8080/hello[window="_blank"], you should see an error with a stacktrace like this:

[.console-output]
[source,text]
----
javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: greeting
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:37)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties61.deploy_0(ConfigBuildStep$validateConfigProperties61.zig:120)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties61.deploy(ConfigBuildStep$validateConfigProperties61.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:166)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:99)
	at java.base/java.lang.Thread.run(Thread.java:834)
----

Which is expected, since we didn't provide the `greeting` property neither at the `application.properties` file nor with some runtime configuration.

== Adding a config property to `application.properties`

Since we requested a `greeting` property in our code, let's provide a value to it in our `application.properties` file available in `src/main/resources`:

[.console-input]
[source,properties]
----
# Configuration file
# key = value
greeting=Hello y'all!
----

Refresh your browser pointing to http://localhost:8080/hello[window="_blank"]. You should see the `Hello y'all!` string.

You can also use `curl` to check the same result:

[.console-input]
[source,bash]
----
curl localhost:8080/hello
----

[.console-output]
[source,text]
----
Hello y'all!
----

== Update your integration test

Since we changed the output of our `/hello` endpoint, our integration test doesn't pass anymore.

Let's update `GreetingResourceTest` to reflect our recent changes:

[.console-input]
[source,java]
----
package com.redhat.developers;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class GreetingResourceTest {

    @Test
    public void testGreetingEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)
             .body(is("Hello y'all!"));
    }

}
----

Stop your current Live Coding session of Quarkus in the terminal by sending a `CTRL+C`:

[.console-output]
[source,text]
----
^C2020-05-11 08:33:41,865 INFO  [io.quarkus] (Quarkus Main Thread) tutorial-app stopped in 0.007s
----

Now run your tests to check if everything is ok:

[tabs]
====
Maven::
+ 
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mvn clean test
----

--
Quarkus CLI::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
quarkus test
----
--
====

[.console-output]
[source,text]
----

[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.851 s
[INFO] Finished at: 2020-05-11T21:31:31-04:00
[INFO] ------------------------------------------------------------------------
----

`BUILD SUCCESS`! You can now go back to the amazing _Live Coding_ mode of Quarkus:

[tabs]
====
Maven::
+ 
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mvn quarkus:dev
----

--
Quarkus CLI::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
quarkus dev
----
--
====
