= Health Check

We can add `{quarkus-health-ext-name}` extension to allow Quarkus application to be probed on the REST endpoint called `health` to know about its current health.

To add `{quarkus-health-ext-name}` to the Quarkus application, run the following command from `{quarkus-project-name}` project directory:

[#qext-mvn-add-extension]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -Dextension="{quarkus-health-ext-name}"
----

After successful execution of the above command, you will have the following dependency added to the `{quarkus-project-name}` project's pom.xml:

.pom.xml 
[.console-input]
[source,xml]
----
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
----

[#qext-health-check-default-run-quarkus-app-dev-mode]
=== Run Quarkus Application in Development mode

:section-build-run: health-check-default

include::ROOT:partial$run-dev-mode.adoc[]

[#qext-call-health-ep]
=== Invoke Service
:doc-sec: basics-health-check
:k8s-cli: k8s
:path: health
:k8s-env: minikube
:cli-tool: curl
:address: localhost

The simple `{path}` REST URI can be called via browser using `http://localhost:8080/{path}` or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[.console-output]
[source,json]
----
{
    "checks": [],
    "outcome": "UP"
}
----

Then you can stop the App by typing kbd:[Ctrl+C].

[#qext-custom-health-check]
=== Customizing Health Checks

So far, you've seen that some a default health check is provided but in most cases, you'd like to customize this logic providing custom logic.
Moreover, Kubernetes provides the concept of liveness and readiness probe to regularly check the health of the application.

liveness:: Checks if the application is up and running.
readiness:: Checks if the application can receive public requests.

Let's create a custom check for both liveness and readiness checks.
Add new Java file in `$PROJECT_HOME/src/main/java/com/example` called `FruitHealthCheck` with the following contents:

[#quarkusp-fruit-checks]
[.console-input]
[source,java,subs="+macros,+attributes"]
----
package com.example;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;

import org.eclipse.microprofile.health.HealthCheck;
import org.eclipse.microprofile.health.Liveness;
import org.eclipse.microprofile.health.Readiness;

import io.smallrye.health.HealthStatus;

@ApplicationScoped
public class FruitHealthCheck {

    @Produces
    @ApplicationScoped
    @Liveness
    HealthCheck liveCheck() {
      return HealthStatus.up("successful-live");
    }

    @Produces
    @ApplicationScoped
    @Readiness
    HealthCheck readyCheck() {
      return HealthStatus.state("successful-read", this::isReady);
    }

    private boolean isReady() {
        return true;
    }
}
----

[#qext-health-check-custom-run-quarkus-app-dev-mode]
=== Run Quarkus Application in Development mode

:section-build-run: health-check-custom

include::ROOT:partial$run-dev-mode.adoc[]

[#qext-call-health-custom]
=== Invoke Service
:doc-sec: custom-health
:k8s-cli: k8s
:path: health
:k8s-env: minikube
:cli-tool: curl
:address: localhost

The simple `{path}` REST URI can be called via browser using `http://localhost:8080/{path}` or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[.console-output]
[source,json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "successful-live",
            "status": "UP"
        },
        {
            "name": "successful-read",
            "status": "UP"
        }
    ]
}
----

But also you can invoke them individually by calling `/health/live` and `/health/ready`.

:doc-sec: custom-health-live
:path: health/live
include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[.console-output]
[source, json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "successful-live",
            "status": "UP"
        }
    ]
}
----

:doc-sec: custom-health-ready
:path: health/ready
include::ROOT:partial$invoke-service.adoc[tag=call]

The REST call about should return an response like:

[.console-output]
[source, json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "successful-read",
            "status": "UP"
        }
    ]
}
----

Then you can stop the container by typing kbd:[Ctrl+C].

ifndef::workshop[]

[#qext-health-checks-kubernetes]
=== Kubernetes Extension and Health Checks

Kubernetes extension detects that Health Check extension is registered and registers them in generated Kubernetes resource.

:doc-sec: k8s-health-check
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-prep]

:section-k8s: health-check
include::ROOT:partial$k8s-build-deploy.adoc[tag=k8s-delete]
endif::workshop[]