=  Deploying to Kubernetes

IMPORTANT: You will need a public container registry to store your image. If you don't have an account, we recommend you to create a free account at http://quay.io[window=_blank]. Our examples will be using the `quay.io` container registry and the `myrepo` organization, but you should change it to match your configuration.

== Adding the Kubernetes and Jib extensions

You need a container registry that is accessible to your Kubernetes cluster so you can deploy your application in it.

In this chapter we'll be using the Quarkus Kubernetes extension to create our Kubernetes files, and we'll be using the Quarkus Jib extension to create and push the container image to our container registry without the need for a local running docker daemon.

Let's add the required extensions:

[.console-input]
[source,bash]
----
./mvnw quarkus:add-extension -Dextensions=quarkus-kubernetes,quarkus-container-image-jib
----

[.console-output]
[source,text]
----
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< com.redhat.developers:tutorial-app >-----------------
[INFO] Building tutorial-app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.4.2.Final:add-extension (default-cli) @ tutorial-app ---
✅ Adding extension io.quarkus:quarkus-kubernetes
✅ Adding extension io.quarkus:quarkus-container-image-jib
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.744 s
[INFO] Finished at: 2020-05-11T21:34:00-04:00
[INFO] ------------------------------------------------------------------------
----

== Adding the Kubernetes extension properties

Add the following Kubernetes properties to your `application.properties` so that it looks like:

IMPORTANT: Change `quay.io` to your container registry and `myrepo` to your organization. If you don't, your push *will* fail.

[.console-input]
[source,properties]
----
# Configuration file
# key = value
greeting=Hello y'all!
quarkus.datasource.url=jdbc:h2:mem:default
quarkus.datasource.driver=org.h2.Driver
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.container-image.registry=quay.io
quarkus.container-image.group=myrepo
quarkus.container-image.name=tutorial-app
quarkus.container-image.tag=1.0-SNAPSHOT
quarkus.kubernetes.service-type=load-balancer
----

== Authenticating and pushing the image to your container registry

In order to push the container image that will be created by the `quarkus-container-image-jib` extension, you'll need to authenticate to your container registry:

[.console-input]
[source,bash]
----
docker login quay.io
----

Now create and push your container image using jib:

[.console-input]
[source,bash]
----
./mvnw clean package -DskipTests -Dquarkus.container-image.push=true
----

[.console-output]
[source,text]
----
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:b459cc59d6c7ddc9fd52f981fc4c187f44a401f2433a1b4110810d2dd9e98a07
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -Dquarkus.http.host=0.0.0.0, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -cp, /app/resources:/app/classes:/app/libs/*, io.quarkus.runner.GeneratedMain]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Pushed container image quay.io/myrepo/tutorial-app:1.0-SNAPSHOT (sha256:6651a2f85f8f53ef951b3398d00f1c7da73bd0e8b21f87584d5a1c0e99aae12c)

[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 14804ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.431 s
[INFO] Finished at: 2020-05-11T00:05:25-04:00
[INFO] ------------------------------------------------------------------------
----

== Deploy your application to your Kubernetes cluster

[.console-input]
[source,bash]
----
kubectl apply -f target/kubernetes/kubernetes.yml
----

[.console-output]
[source,text]
----
serviceaccount/tutorial-app created
service/tutorial-app created
deployment.apps/tutorial-app created
----

You might need to wait for some seconds until your application is up and running.

[tabs]
====
Minikube::
+
--
:tmp-service-exposed: tutorial-app

[#{section-k8s}-ip-port-minikube]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(minikube ip)
PORT=$(kubectl get service/{tmp-service-exposed} -o jsonpath="{.spec.ports[*].nodePort}")
echo $IP:$PORT
----
--
Hosted::
+
--
If using a hosted Kubernetes cluster like OpenShift then use curl and the EXTERNAL-IP address with port `8080` or get it using `kubectl`:

:tmp-service-exposed: tutorial-app

[#{section-k8s}-ip-port-openshift]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(kubectl get service {tmp-service-exposed} -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
PORT=$(kubectl get service {tmp-service-exposed} -o jsonpath="{.spec.ports[*].port}")
echo $IP:$PORT
----
--
Hosted on AWS::
+
--
If using a hosted Kubernetes cluster like OpenShift then use curl and the EXTERNAL-IP address with port `8080` or get it using `kubectl`:

:tmp-service-exposed: tutorial-app

[#{section-k8s}-ip-port-openshift]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(kubectl get service {tmp-service-exposed} -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
PORT=$(kubectl get service {tmp-service-exposed} -o jsonpath="{.spec.ports[*].port}")
echo $IP:$PORT
----
--
====

Curl the Service:

[#{section-k8s}-curl-the-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/hello
----

[.console-output]
[source,text]
----
Hello y'all!
----