= Security with JWT RBAC

== Securing endpoints with JWT

In a microservices architecture, and generally speaking, any kind of application, might need to be protected so only certain users can access to the defined endpoint.
Quarkus provides an integration to the https://github.com/eclipse/microprofile-jwt-auth[MicroProfile JWT RBAC] spec.

So let's see how you can start using JWT for role based access control (RBAC) of endpoints.

[#qext-add-jwt-extensions]
=== Adding JWT RBAC extension

:quarkus-jwt-ext-name: quarkus-smallrye-jwt

To add JWT RBAC extension (`{quarkus-jwt-ext-name}`) to the Quarkus application, run the following command from `{quarkus-project-name}` project directory:

[#qext-mvn-add-jwt-extension]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -Dextension="{quarkus-jwt-ext-name}"
----

[#qext-configure-jwt-parameters]
=== Configuring JWT parameters

Add the following properties to `pass:[$PROJECT_HOME]/src/main/resources/application.properties`:

[.console-input]
[source,properties]
----
mp.jwt.verify.publickey.location=https://raw.githubusercontent.com/redhat-developer-demos/quarkus-tutorial/master/jwt-token/quarkus.jwt.pub.jwk.json
mp.jwt.verify.issuer=https://quarkus.io/using-jwt-rbac
----

We are also providing a valid token that can be verified by the configured public key:

[.console-output]
[source, javascript]
----
{
  "kid": "/privateKey.pem",
  "typ": "JWT",
  "alg": "RS256"
},
{
  "sub": "jdoe-using-jwt-rbac",
  "aud": "using-jwt-rbac",
  "upn": "jdoe@quarkus.io",
  "birthdate": "2001-07-13",
  "auth_time": 1570094171,
  "iss": "https://quarkus.io/using-jwt-rbac", // <1>
  "roleMappings": {
    "group2": "Group2MappedRole",
    "group1": "Group1MappedRole"
  },
  "groups": [ // <2>
    "Echoer",
    "Tester",
    "Subscriber",
    "group2"
  ],
  "preferred_username": "jdoe",
  "exp": 2200814171,
  "iat": 1570094171,
  "jti": "a-123"
}
----
<1> The issuer you set in `application.properties`
<2> `groups` field is used by `MicroProfile JWT RBAC` to get the access groups (or roles) that the owner of the token has

[#qext-jwt-inject-claim]
=== Inject claims into an Object

You can inject any defined claim into an object by using `@Claim` annotation:

Open `pass:[$PROJECT_HOME]/src/main/java/java/com/example/FruitResource.java` and inject username claim:

[#quarkussec-jwt-claim-username]
[.console-input]
[source,config,subs="+macros"]
----
@Inject @Claim(standard = Claims.preferred_username)
String username;

@GET
@Path("/claim")
public String getClaim() {
    return username;
}
----

Rename the `@Path` used in `FruityVice getFruitInfoByName` to `@Path("name-{name})"` to avoid conflict with the path `/fruit/claim`.

[#qext-jwt-claim-quarkus-app-dev-mode]
== Run Quarkus Application in Development mode

:section-build-run: jwt-claim-dev

include::ROOT:partial$run-dev-mode.adoc[]

[#qext-call-jwt-claim]
=== Invoke Service
:doc-sec: jwt-claim
:k8s-cli: k8s
:path: fruit/claim
:k8s-env: minikube
:cli-tool: curl
:address: localhost
:token-url: https://gist.githubusercontent.com/lordofthejars/9a0b47298c807739a9eb1adfba50795e/raw/5f8c5b7a9c11ed455f4910ed2032d79612b5e6f6/quarkus.jwt.token
:token-value: $(curl {token-url} -s)

The simple `{path}` REST URI can be called via browser using http://localhost:8080/{path} or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=callToken]

And you'll see the `preferred_username` field for the given token (`jdoe`).

MircoProfile JWT RBAC spec is providing out-of-the-box the validation of the given token. 
These validations include for example that the token has not been modified, has not expired or the issuer is the expected one.

To validate this just invoke again the service but changing the token:

:token-value: XXXX

include::ROOT:partial$invoke-service.adoc[tag=callToken]

And now the invocation returns and HTTP code `401 Unauthorized` because the token is invalid.

[#qext-jwt-inject-rbac]
=== Adds RBAC to the endpoint

So far, you've seen how to get claims from the provided JWT token, but anyone could access that endpoint, let's protected it with a role.
For this case you need to use a role that is defined in JWT token into `groups` claim (ie `Subscriber`).

Open `pass:[$PROJECT_HOME]/src/main/java/java/com/example/FruitResource.java` and annotate the method with `javax.annotation.security.RolesAllowed`:

[#quarkussec-jwt-rbac]
[.console-input]
[source,config,subs="+macros"]
----
@GET
@Path("/claim")
@RolesAllowed("Subscriber")
public String getClaim() {
    return username;
}
----

[#qext-call-jwt-rbac]
=== Invoke Service

[.console-input]
[source,bash]
----
token=$(curl https://raw.githubusercontent.com/redhat-developer-demos/quarkus-tutorial/master/jwt-token/quarkus.jwt.pub.jwk.json -s)
curl -H "Authorization: Bearer $token" localhost:8080/beer
----

Open `pass:[$PROJECT_HOME]/src/main/java/java/com/example/FruitResource.java` and change the  `RolesAllowed` value to `Subscriber2`:

[#quarkussec-jwt-rbac-invalid]
[.console-input]
[source,config,subs="+macros"]
----
@GET
@Path("/claim")
@RolesAllowed("Subscriber2")
public String getClaim() {
    return username;
}
----

And then do the request again:

The simple `{path}` REST URI can be called via browser using http://localhost:8080/{path} or using CLI like: 

include::ROOT:partial$invoke-service.adoc[tag=callToken]

And the output now is different: `Forbidden`.

This is the result because the provided token does not contain `Subscriber2` in the `groups` claim.
