[[requirements]]
= Setup
include::../_attributes.adoc

== IDE

You can use any Java IDE for this tutorial but if you didn't try it before, we recommend https://code.visualstudio.com/download[VS Code, window="_blank"] with the https://marketplace.visualstudio.com/items?itemName=redhat.java[Language Support for Java(TM) by Red Hat, window="_blank"] and the https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus[Quarkus, window="_blank"] extensions.

[TIP]
====
If you are using VS Code, then install the VS Code https://aka.ms/vscode-remote/download/extension[Remote Development Extension pack],
which allows you to run this entire tutorial within a container that will have all tools configured.
====

== CLI Tools

The following CLI tools are required for running the exercises in this tutorial.

////
ifndef::workshop[]
Kubernetes/OpenShift are required only in case you want to deploy the application into them.
endif::workshop[]
////

[TIP]
====
GraalVM is only required if you intend to build a native image for your local operating system. If you want to create a container using a native image, you can use the Quarkus feature for this and don't need to install GraalVM locally.
====

TIP: You can also use Docker instead of Podman. The advantage of Podman is that it is 100% Free Open Source and does not need to run with elevated privileges. Just use 'docker' instead of 'podman' throughout the tutorial's instructions.

[tabs]
====
Local  Installation::
+
--
Please have them installed and configured before you get started with any of the tutorial chapters.

[options="header"]
|===
|**Tool**|**macOS**|**Fedora**|**Windows**

| **Podman Desktop**
| https://podman-desktop.io/downloads[Podman Desktop for Mac, window="_blank"]
| https://podman-desktop.io/downloads[Podman Desktop for Linux, window="_blank"]
| https://podman-desktop.io/downloads[Podman Desktop for Windows, window="_blank"]

| **Java 17**
| `brew tap AdoptOpenJDK/openjdk && brew cask install adoptopenjdk17`
| `dnf install java-17-openjdk.x86_64`
| https://adoptopenjdk.net[Windows] (Make sure you set the `JAVA_HOME` environment variable and add `%JAVA_HOME%\bin` to your `PATH`)

| **Apache Maven 3.8.1+**
| `brew install maven`
| `dnf install maven`
| https://maven.apache.org/download.cgi[Windows] (Make sure you set the `MAVEN_HOME` environment variable and add `%MAVEN_HOME%\bin` to your `PATH`)

| **Graal VM**
| https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-{graalvm-version}/graalvm-ce-java17-darwin-amd64-{graalvm-version}.tar.gz[GraalVM Community Edition {graalvm-version}]
| https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-{graalvm-version}/graalvm-ce-java17-linux-amd64-{graalvm-version}.tar.gz[GraalVM Community Edition {graalvm-version}]
| https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-{graalvm-version}/graalvm-ce-java17-windows-amd64-{graalvm-version}.zip[GraalVM Community Edition {graalvm-version}]

|===
--
Container Image::
+
--
If you have https://podman-desktop.io/downloads[Podman Desktop for Linux, window="_blank"]  then you can pull the Linux container image 
https://quay.io/repository/rhdevelopers/tutorial-tools?tab=tags[tutorial tools] which has all the tools listed below installed and pre-configured.
[#podman-pull-tutorials-cli]
[source,bash]
-----
podman pull quay.io/rhdevelopers/tutorial-tools
mkdir quarkus-tutorial
cd quarkus-tutorial
mkdir work
podman run -ti -p 8080:8080 -v `pwd`/work:/work \
  -v `mvn help:evaluate -Dexpression=settings.localRepository | grep \
  -v '\[INFO\]' | grep -v '\[WARNING\]'`:/opt/developer/.m2/repository \
  --rm quay.io/rhdevelopers/tutorial-tools bash

# -p will map Quarkus running in the container to your host port
# -v `pwd`... will map the host work subdirectory to the container /work directory, this is where you will create your application
# -v `mvn ...` will map your ~/.m2/repository of your host to the container repository to save downloading again between image runs
-----
--
====

////
ifndef::workshop[]
[#remote-podman-repository]
== Remote Repository
For some parts of the tutorial, you will be pushing and pulling container images to and from a remote image repository. You will need an account with push rights. You can create a free account on https://quay.io[Red Hat Quay.io].
endif::workshop[]

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start setting up the environment, let's clone the tutorial sources and set the `TUTORIAL_HOME` environment variable to point to the root directory of the tutorial:

[#cloneRepo]
[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/quarkus-tutorial 
----

The `work` folder in `$TUTORIAL_HOME` can be used to download the demo application resources and refer to them during the exercises. The `work` folder has a README with instructions on the source code repo and git commands to clone the sources.

NOTE: if you use `tutorial-tools`, this step is optional.

[IMPORTANT,subs="+macros,+attributes"]
====

This tutorial was developed and tested with:

- Quarkus `{quarkus-version}`
- Minikube `{minikube-version}`
- OpenShift `{openshift-version}`
- Minishift `{minishift-version}`
- Graal VM `{graalvm-version}`
====

ifndef::workshop[]
[#kubernetes-cluster]
== Kubernetes Cluster

[tabs]
====
Minikube::
+
--
[#quarkus-start-minikube]
[source,bash,subs="+macros,+attributes"]
----
minikube profile quarkus-tutorial && \
minikube -p quarkus-tutorial start --memory=8192 --cpus=4 --disk-size=50g && \
kubectl create namespace {tutorial-namespace}
kubectl config set-context --current --namespace={tutorial-namespace}
----
--
Minishift::
+
--
[#quarkus-start-minishift]
[source,bash,subs="+macros,+attributes"]
----
minishift profile set quarkus-tutorial && \
minishift start --memory=8192 --cpus=4 --disk-size=50g && \
minishift addon enable admin-user && \
minishift addon enable anyuid && \
oc new-project {tutorial-namespace}
----
--
====

[NOTE]
====
On macOS, you might need to install hyperkit and  pass it as the main engine adding `--vm-driver=hyperkit` after `--disk-size=50g`.
====

Prepare your shell environment

[#quarkus-tutorial-shell-env]
[source,bash,subs="+macros,+attributes"]
----
cd quarkus-tutorial
export TUTORIAL_HOME=pass:[`pwd`]
export GRAALVM_HOME='PUT THE LOCATION  WHERE YOU HAVE EXTRACTED GRAAL VM'
----

Prepare your shell environment:

It is not necessary to install GraalVM as the native compilation can be done within a container.
The only limitation, in this case, is to have Podman/Docker installed and the produced native executable will only be runnable inside a container.
GraalVM is already installed in `tutorial-tools`.

If you installed GraalVM, make sure to also install `native-image` 

[#quarkus-tutorial-graalvm-native]
[source,bash,subs="+macros,+attributes"]
----
gu install native-image
----


[#quarkus-tutorial-shell-env]
[source,bash,subs="+macros,+attributes"]
----
cd quarkus-tutorial
export TUTORIAL_HOME=pass:[`pwd`]
export WORKSHOP_USER='PUT YOUR USERNAME HERE'
export GRAALVM_HOME='PUT THE LOCATION  WHERE YOU HAVE EXTRACTED GRAAL VM'
export WORKSHOP_OPENSHIFT_SERVER='PUT THE OPENSHIFT SEVER URL HERE'
----

Login into OpenShift 
[#quarkus-tutorial-oc-login]
[source,bash,subs="+macros,+attributes"]
----
oc login --username pass:[$WORKSHOP_USER] --server pass:[$WORKSHOP_OPENSHIFT_SERVER] --insecure-skip-tls-verify=false
----

ifdef::openshift-console-url[]
You can also access the Openshift Console via url {openshift-console-url}
endif::[]

IMPORTANT: If you are in `MAC OSX`, the variable should point to `Home` sub-directory: `export GRAALVM_HOME=$HOME/Development/graalvm/Contents/Home/`
endif::workshop[]

[#setup-work-folder]
== Work folder (Optional)

The work folder i.e `$TUTORIAL_HOME/work` can be used as a work directory during the build. 
////
