apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:bionic
        env:
        -  name: "MYSQL_ROOT_PASSWORD"
           value: "superS3cret!"
        -  name: "MYSQL_USER"
           value: "demo"
        -  name: "MYSQL_PASSWORD"
           value: "password"
        -  name: "MYSQL_DATABASE"
           value: "demodb" 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: db-adminer
spec:
  selector:
    app: db-adminer
  ports:
  - port: 9090
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-adminer
spec:
  selector:
    matchLabels:
      app: db-adminer
  template:
    metadata:
      labels:
        app: db-adminer
    spec:
      containers:
      - name: db-adminer
        image: adminer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
