NOTE: The instructions of this section assumes your project name to be `{quarkus-project-name}`

#tag::build[]

[tabs]
====
JVM mode::
+
--
[#conk8s-build-quarkus-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
./mvnw -DskipTests clean package
----
copyToClipboard::conk8s-build-quarkus-jvm-app[]

After successful maven build, run the following command to build te container:

[#conk8s-build-quarkus-jvm-app-container]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.jvm -t example/{quarkus-project-name}:1.0-SNAPSHOT .
----
copyToClipboard::conk8s-build-quarkus-jvm-app-container[]

--
Native mode::
+
--
[#conk8s-build-quarkus-native-app]
[source,bash,subs="+macros,+attributes"]
----
./mvnw -DskipTests clean package -Pnative -Dnative-image.docker-build=true <1>
----
copyToClipboard::conk8s-build-quarkus-native-app[]
<1> Using the `-Dnative-image.docker-build=true` is very important as need a linux native binary what will be containerized. 

NOTE: Native compilation will take few minutes to complete.

After successful maven build, run the following command to build te container:

[#conk8s-build-quarkus-native-app-container]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.native -t example/{quarkus-project-name}:1.0-SNAPSHOT .
----
copyToClipboard::conk8s-build-quarkus-native-app-container[]

--
====

#end::build[]


#tag::run[]

[#build-run-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm -p 8080:8080 example/{quarkus-project-name}:1.0-SNAPSHOT
----
copyToClipboard::build-run-jvm-app[]

#end::run[]

#tag::tag-push[]

[#build-tag-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
docker push example/{quarkus-project-name}:1.0-SNAPSHOT
----
copyToClipboard::build-tag-jvm-app[]

#end::tag-push[]