NOTE: The instructions of this section assumes your project name to be `{quarkus-project-name}`

#tag::build[]

[tabs]
====
JVM mode::
+
--
[#{section-k8s}-build-quarkus-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
./mvnw -DskipTests clean package
----

After successful maven build, run the following command to build the container - choose the terminal of the target environment you wish to use (docker, minishift or minokube) as you want to build and publish the image in the right registry:

[#{section-k8s}-build-quarkus-jvm-app-container]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.jvm -t example/{quarkus-project-name}:1.0-SNAPSHOT .
----

--
Native mode::
+
--
[#{section-k8s}-build-quarkus-native-app]
[source,bash,subs="+macros,+attributes"]
----
./mvnw -DskipTests clean package -Pnative -Dnative-image.docker-build=true <1>
----
<1> Using the `-Dnative-image.docker-build=true` is very important as need a linux native binary what will be containerized. 

NOTE: Native compilation will take few minutes to complete.

After successful maven build, run the following command to build the container - choose the terminal of the target environment you wish to use (docker, minishift or minokube) as you want to build and publish the image in the right registry:

[#{section-k8s}-build-quarkus-native-app-container]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.native -t example/{quarkus-project-name}:1.0-SNAPSHOT .
----

--
====

NOTE: For sake of simplicity the container name in both native and jvm mode are named identically. In real cases where you might need both containers, you'd like to name them differently to know exactly the package they are containing.

#end::build[]


#tag::run[]

[#{doc-sec}-run-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm -p 8080:8080 example/{quarkus-project-name}:1.0-SNAPSHOT
----

#end::run[]

#tag::tag-push[]

[#{doc-sec}-tag-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
docker push example/{quarkus-project-name}:1.0-SNAPSHOT
----

#end::tag-push[]
