[tabs]
====
JVM mode::
+
--
[#basics-build-quarkus-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
cd pass:[$TUTORIAL_HOME]/work/{project-dir} && \
./mvnw -DskipTests clean package
----
copyToClipboard::basics-build-quarkus-jvm-app[]

To run the application in jvm mode

[#basics-build-run-jvm-app]
[source,bash,subs="+macros,+attributes"]
----
java -jar target/{project-dir}-1.0-SNAPSHOT-runner.jar
----
copyToClipboard::basics-build-run-jvm-app[]

--
Native mode::
+
--
[#basics-build-quarkus-native-app]
[source,bash,subs="+macros,+attributes"]
----
cd pass:[$TUTORIAL_HOME]/work/{project-dir} && \
./mvnw -DskipTests clean package -Pnative
----
copyToClipboard::basics-build-quarkus-native-app[]

NOTE: Native compilation will take few minutes to complete.

To run the application in native mode

[#basics-build-run-native-app]
[source,bash,subs="+macros,+attributes"]
----
./target/{project-dir}-1.0-SNAPSHOT-runner
----
copyToClipboard::basics-build-run-native-app[]

[IMPORTANT]
=====
Tests will fail on Windows as there is no graalvm support for windows, you can workaround it using `-DskipTests` option.
=====

--
Native container-build mode::
+
--
[#basics-build-quarkus-native-docker-app]
[source,bash,subs="+macros,+attributes"]
----
cd pass:[$TUTORIAL_HOME]/work/{project-dir} && \
./mvnw package -DskipTests -Pnative -Dquarkus.native.container-build=true
----
copyToClipboard::basics-build-quarkus-native-docker-app[]

NOTE: Native compilation will take few minutes to complete.

To run the application in native mode you need to build a Docker image using the native file generated in previous step:

[#basics-build-run-native-docker-app]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.native -t example/{quarkus-project-name}:1.0-SNAPSHOT . && \
docker run -it --rm -p 8080:8080 example/{quarkus-project-name}:1.0-SNAPSHOT
----
copyToClipboard::basics-build-run-native-docker-app[]

--
====
