[tabs%sync]
====
JVM mode::
+
--

[%header,cols="1,1"]
|=====

|Maven

|Quarkus CLI

a|
[#basics-build-quarkus-jvm-app-mvn]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
 mvn package 
----

a|
[#basics-build-quarkus-jvm-app-quarkus]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
quarkus build
----

|=====


To run the application in jvm mode

[#basics-build-run-jvm-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
java -jar target/quarkus-app/quarkus-run.jar
----

--
Native mode::
+
--

Quarkus simplifies the https://quarkus.io/guides/building-native-image[compilation of Java applications down to a native binary] using GraalVM/Mandrel. To do so, add a "native" flag to your build command.   

NOTE: To force building a native binary in a GraalVM Mandrel container, add `-Dquarkus.native.container-build=true`.  

[%header,cols="1,1"]
|=====

|Maven

|Quarkus CLI

a|
[#basics-build-quarkus-native-app-mvn]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
 mvn package -Dnative
----

a|
[#basics-build-quarkus-native-app-quarkus]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
quarkus build --native
----
|=====


NOTE: Native compilation will take few minutes to complete.

To run the application in native mode

[#basics-build-run-native-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./target/{project-name}-1.0-SNAPSHOT-runner
----

--
Native container-build mode::
+
--

[%header,cols="1,1"]
|=====
|Maven

|Quarkus CLI

a|
[#basics-build-quarkus-native-container-app-mvn]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
 mvn quarkus:image-build \
  -Dnative
----
a|
[#basics-build-quarkus-native-container-app-quarkus]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
quarkus image build --native 
----
|=====

NOTE: Native compilation will take few minutes to complete.

The above command will build a native binary of the Java code and then copy it into a container image.
Start the container that runs the native binary:

[#basics-build-run-native-docker-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm -p 8080:8080 {project-name}:1.0-SNAPSHOT
----

--
====

You'll see an output like this one:

[.console-output]
[source,text]
----
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-07-07 11:47:14,046 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 3.2.0.Final) started in 0.019s. Listening on: http://0.0.0.0:8080
2023-07-07 11:47:14,047 INFO  [io.quarkus] (main) Profile prod activated. 
2023-07-07 11:47:14,047 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, smallrye-context-propagation, vertx]
----