[:quarkus-project-name='']

#tag::k8s-prep[]

[IMPORTANT]
====
If you have not deployed the application previously, you need to add Quarkus Kubernetes extension. This extension uses https://github.com/dekorateio/dekorate[Dekorate] to generate a default Kubernetes resource template.

[#qext-mvn-add-kubernetes-extension]
[source,bash,subs="+macros,+attributes"]
----
./mvnw quarkus:add-extension -Dextensions="quarkus-kubernetes"
----
copyToClipboard::qext-mvn-add-kubernetes-extension[]

You need to configure group and name of the Docker container used to deploy into Kubernetes.

Add the following properties (if you haven't already done it before) to pass:[$PROJECT_HOME]/src/main/resources/application.properties:

[#quarkusk8s-update-props]
[source,config,subs="+macros,+attributes"]
----
quarkus.kubernetes.group=example
quarkus.application.name={quarkus-project-name}
----
copyToClipboard::quarkusk8s-update-props[]

====

Now you need to run Maven goal to generate Kubernetes resource.

[#quarkusk8s-generate-kubernetes]
[source,bash,subs="+macros,+attributes"]
----
./mvnw package -DskipTests
----
copyToClipboard::quarkusk8s-generate-kubernetes[]

You can inspect the generated file by accessing next file:

[#quakrusk8s-generated-kubernetes-resource]
[source,bash,subs="+macros,+attributes"]
----
cat pass:[$TUTORIAL_HOME]/target/wiring-classes/META-INF/kubernetes/kubernetes.json
----
copyToClipboard::quakrusk8s-generated-kubernetes-resource[]

#end::k8s-prep[]

#tag::k8s-deploy[]

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#conk8s-run-deploy-k8s-app]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f pass:[$TUTORIAL_HOME]/target/wiring-classes/META-INF/kubernetes/kubernetes.json
----
copyToClipboard::conk8s-run-deploy-k8s-app[]
--
oc::
+
--
endif::[]

[#conk8s-oc-run-deploy-k8s-app]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f pass:[$TUTORIAL_HOME]/target/wiring-classes/META-INF/kubernetes/kubernetes.json
----
copyToClipboard::conk8s-oc-run-deploy-k8s-app[]
ifndef::workshop[]
--
====
endif::[]

#end::k8s-deploy[]


#tag::k8s-invoke-svc[]

ifndef::workshop[]
[tabs]
====
kubectl::
+
--

You need to create a `NodePort` to expose the application if you are in minikube.
As generated resources creates a `ClusterIP` service, you need to patch it:

[#conk8s-k8s-run-expose-svc-nodeport]
[source,bash,subs="+macros,+attributes"]
----
kubectl patch svc {quarkus-project-name} --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"}]'
----
copyToClipboard::conk8s-k8s-run-expose-svc-nodeport[]

[#conk8s-run-deploy-k8s-service]
[source,bash,subs="+macros,+attributes"]
----
SVC_URL=$(minikube service -n quarkustutorial {quarkus-project-name} --url)
----
copyToClipboard::conk8s-run-deploy-k8s-service[]

--
oc::
+
--
endif::[]
With OpenShift we can create a route to make Quarkus application publicly accessible:

[#conk8s-oc-run-expose-svc-route]
[source,bash,subs="+macros,+attributes"]
----
oc expose service {quarkus-project-name}
----
copyToClipboard::conk8s-oc-run-expose-svc-route[]

Once the service is exposed we can use the following command to get the public url:

[#conk8s-oc-run-get-route]
[source,bash,subs="+macros,+attributes"]
----
SVC_URL=$(oc get routes {quarkus-project-name} -o jsonpath='{.spec.host}')
----
copyToClipboard::conk8s-oc-run-get-route[]
ifndef::workshop[]
--
====
endif::[]

Now you can use the `SVC_URL` to call the service from the browser or via cli like:

[#conk8s-call-k8s-svc]
[source,bash,subs="+macros,+attributes"]
----
curl $SVC_URL/{svc-path}
----
copyToClipboard::conk8s-call-k8s-svc[]

#end::k8s-invoke-svc[]

#tag::k8s-delete[]

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#conk8s-delete-k8s-app]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete all --all
----
copyToClipboard::conk8s-delete-k8s-app[]
--
oc::
+
--
endif::[]

[#conk8s-delete-oc-app]
[source,bash,subs="+macros,+attributes"]
----
oc delete all --all
----
copyToClipboard::conk8s-delete-oc-app[]
ifndef::workshop[]
--
====
endif::[]

#end::k8s-delete[]